### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by imshuffling** [mgschoen/contentful-reference-matrix-field-app#3]
Hey @mgschoen, just wanted to say loving this App. It's a really good starting point for a lot of use cases.

I've forked the ingredients repo locally and have integrated beautiful DND into it. Would you want me to submit this as a PR?

**Comment by mgschoen** [comment]
Hi @imshuffling, very cool idea! I'd love to see it and would be happy if you could submit :)

**Comment by imshuffling** [comment]
Great @mgschoen - Just submitted a PR :)
